// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuMv6lYQAxNzTe6Ihfk0Y-moZI4STkgaY',
    appId: '1:340927249915:web:65498649b18e11f1e8df5e',
    messagingSenderId: '340927249915',
    projectId: 'tourism-chat-89431',
    authDomain: 'tourism-chat-89431.firebaseapp.com',
    storageBucket: 'tourism-chat-89431.firebasestorage.app',
    measurementId: 'G-SMXW9HKF65',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDe2S_YDuvOe7ZSxkQcPra6n1_EtQPNjuE',
    appId: '1:340927249915:android:aaeeb6b4627dcaf8e8df5e',
    messagingSenderId: '340927249915',
    projectId: 'tourism-chat-89431',
    storageBucket: 'tourism-chat-89431.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBE4BApfYKiGwZe-y9RuBknG8yNV0YqGMI',
    appId: '1:340927249915:ios:0e2693505e62fbf6e8df5e',
    messagingSenderId: '340927249915',
    projectId: 'tourism-chat-89431',
    storageBucket: 'tourism-chat-89431.firebasestorage.app',
    iosBundleId: 'com.example.tourismChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuMv6lYQAxNzTe6Ihfk0Y-moZI4STkgaY',
    appId: '1:340927249915:web:051f9c88190b601fe8df5e',
    messagingSenderId: '340927249915',
    projectId: 'tourism-chat-89431',
    authDomain: 'tourism-chat-89431.firebaseapp.com',
    storageBucket: 'tourism-chat-89431.firebasestorage.app',
    measurementId: 'G-X0L13LRQM0',
  );
}
